name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Add Arduboy board
      run: arduino-cli config init --additional-urls https://arduboy.github.io/board-support/package_arduboy_index.json

    - name: install Arduboy board
      run: arduino-cli core update-index && arduino-cli core upgrade arduino:avr && arduino-cli core upgrade arduboy:avr

    - name: build
      run: arduino-cli compile --fqbn "arduboy:avr:arduboy"  .  --output-dir .