name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: ./setup.sh

    - name: configure
      run: cd build && ./build.sh

    - name: test
      run: ./test.sh
