name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install gtest manually
      run: ./setup.sh

    - name: configure
      run: cd build && cmake -DUSE_DEBUG=ON . && make all
  
    - name: test
      run: cd build && ./tst/CreatureGathererFX_tst
